# Generated by Django 5.1.2 on 2024-10-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_animal', '0002_alter_perfil_cedula_alter_perfil_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cedula',
            field=models.CharField(max_length=20),
        ),
    ]
