# Generated by Django 5.1.2 on 2024-10-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_animal', '0003_perfil_email_alter_perfil_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
