# Generated by Django 5.1.2 on 2024-10-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_animal', '0004_alter_perfil_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
