# Generated by Django 5.1.2 on 2024-10-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_animal', '0007_alter_animalito_ayudador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cedula',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('veterinario', 'Centro Veterinario'), ('hogar_paso', 'Hogar de Paso'), ('adoptante', 'Adoptante'), ('colaborador', 'Colaborador'), ('ayudador', 'Ayudador')], max_length=20),
        ),
    ]
