# Generated by Django 5.1.2 on 2024-10-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_animal', '0008_alter_perfil_cedula_alter_perfil_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalito',
            name='estado',
            field=models.CharField(choices=[('calle', 'En la calle'), ('hogar_paso', 'En hogar de paso'), ('revisado_veterinario', 'Revisado por el veterinario')], default='calle', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cedula',
            field=models.CharField(max_length=20),
        ),
    ]
