# Generated by Django 5.1.2 on 2024-10-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_animal', '0009_animalito_estado_alter_perfil_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalito',
            name='descripcion_veterinario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
