# Generated by Django 5.1.2 on 2024-10-17 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_animal', '0012_alter_animalito_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalito',
            name='ayudador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='animalito',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='animalitos/'),
        ),
    ]
