# Generated by Django 5.1.2 on 2024-10-18 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_animal', '0013_alter_animalito_ayudador_alter_animalito_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalito',
            name='ayudador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_animal.perfil'),
        ),
    ]
