# Generated by Django 5.1.2 on 2024-10-18 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_animal', '0018_remove_solicitudadopcion_fecha_solicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalito',
            name='hogar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animales', to='gestion_animal.perfil'),
        ),
    ]
