# Generated by Django 5.1.2 on 2024-10-18 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_animal', '0019_animalito_hogar'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudadopcion',
            name='hogar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='gestion_animal.perfil'),
        ),
    ]
